[package]
name = "drcon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
nix = "0.25.0"
clap = "3.2.20"
hex = "0.4"
log4rs = "1.1"
pnet = "0.31.0"
log = "0.4"